In [1]:
import gurobipy as gp
from gurobipy import GRB
import numpy as np
import random



#leggo da file la matrice di copertura 
mod = gp.Model('WDCP')
file = open('TEST3.txt', 'r')
content = file.readlines()
A = []
for i in content:
    array = []
    parse = i.split(",")
    for j in parse:
        array.append(float(j))
    A.append(array)
file.close()

numero_righe=len(A)
numero_colonne=len(A[0])
                           



file2 = open('TEST3sj.txt', 'r')
content = file2.readline()
pars1=content.split(",")
s = []
for i in pars1:
    s.append(float(i))
file.close() 
s = np.array(s)  
    


numero_righe=len(A)
numero_colonne=len(A[0])
A = np.array(A)


    
print('A: ',A)
print('righe di A: ',numero_righe)
print('colonne di A: ',numero_colonne)
print('s: ',s)

if (len(s)!=numero_colonne):
    print('errore')


Set parameter Username
Academic license - for non-commercial use only - expires 2024-11-13
A:  [[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 1.]]
righe di A:  1352
colonne di A:  6400
s:  [0. 0. 0. ... 0. 0. 0.]


In [2]:
#parametro alpha per i punti generali
alpha=0.2;

#creazione del modello
mod = gp.Model('WDCP')
L = range(numero_righe)
R = range(numero_colonne)
y = mod.addVars(L,vtype=GRB.BINARY,name="y")
x = mod.addVars(R,vtype=GRB.BINARY,name="x")


# Creazione dell'obiettivo
obj = mod.setObjective(gp.quicksum(y[i] for i in L) - alpha * gp.quicksum((1-s[j])*x[j] for j in R), GRB.MINIMIZE)


#vincoli
for j in R:  
    if s[j]==1: #aggiungo per forza i punti importanti
        mod.addConstr(gp.quicksum(A[i,j]*y[i] for i in L) >= 1)
    else:     #altrimenti, il punto è generale e la sua appartenza alla soluzione dipende da alpha
        mod.addConstr(gp.quicksum(A[i,j] * y[i] for i in L) >= x[j]) 
    for i in L:
        mod.addConstr((A[i,j]*y[i])<=x[j])  #se posiziono la telecamera devo segnare i punti coperti

# Risoluzione del problema
mod.optimize()

# Stampa dei risultati

for i in L:
    print(f"y_{i+1} =", int(y[i].x))

for j in R:
    print(f"x_{j+1} =", int(x[j].x))
    
    



Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 8659200 rows, 7752 columns and 8709792 nonzeros
Model fingerprint: 0x71b55a16
Variable types: 0 continuous, 7752 integer (7752 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e-01, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e+00, 1e+00]
Presolve removed 8654649 rows and 1969 columns
Presolve time: 4.65s
Presolved: 4551 rows, 5783 columns, 23479 nonzeros
Variable types: 0 continuous, 5783 integer (5783 binary)
Found heuristic solution: objective -765.6000000

Root simplex log...

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0   -8.9700000e+02   2.461000e+03   0.000000e+00      6s
    4359   -8.2857652e+02   0.000000e+00   0.000000e+00      6s

Root relaxation: objec

  RLT: 35

Explored 4072 nodes (1570427 simplex iterations) in 268.78 seconds (337.91 work units)
Thread count was 8 (of 8 available processors)

Solution count 10: -817.8 -817.6 -817.4 ... -813.8
No other solutions better than -817.8

Optimal solution found (tolerance 1.00e-04)
Best objective -8.178000000000e+02, best bound -8.178000000000e+02, gap 0.0000%
y_1 = 0
y_2 = 1
y_3 = 1
y_4 = 0
y_5 = 1
y_6 = 1
y_7 = 0
y_8 = 1
y_9 = 0
y_10 = 1
y_11 = 0
y_12 = 1
y_13 = 0
y_14 = 1
y_15 = 1
y_16 = 0
y_17 = 1
y_18 = 0
y_19 = 1
y_20 = 0
y_21 = 1
y_22 = 0
y_23 = 1
y_24 = 1
y_25 = 0
y_26 = 1
y_27 = 1
y_28 = 0
y_29 = 0
y_30 = 0
y_31 = 1
y_32 = 0
y_33 = 0
y_34 = 0
y_35 = 1
y_36 = 0
y_37 = 0
y_38 = 1
y_39 = 0
y_40 = 0
y_41 = 0
y_42 = 1
y_43 = 0
y_44 = 0
y_45 = 0
y_46 = 1
y_47 = 0
y_48 = 0
y_49 = 0
y_50 = 1
y_51 = 0
y_52 = 1
y_53 = 1
y_54 = 0
y_55 = 0
y_56 = 0
y_57 = 0
y_58 = 1
y_59 = 0
y_60 = 0
y_61 = 0
y_62 = 1
y_63 = 0
y_64 = 1
y_65 = 0
y_66 = 0
y_67 = 0
y_68 = 1
y_69 = 0
y_70 = 0
y_71 = 0
y_72 = 1
y

In [3]:
puntivisti=0;
    
for j in R:
    puntivisti=puntivisti+int(x[j].x)

puntiimportanti=0;
    
for j in range(numero_colonne):
    puntiimportanti=puntiimportanti+s[j]

telecameremesse=0;
for i in L:
    telecameremesse=telecameremesse+int(y[i].x)
    
print("numero di posizioni osservate: ",puntivisti) #punti coperti
print("numero telecamere posizionate: ",telecameremesse) 
print("numero punti importanti: ",puntiimportanti) 



numero di posizioni osservate:  6059
numero telecamere posizionate:  384
numero punti importanti:  50.0


In [4]:
#creazione del modello
mod = gp.Model('WDCP')
L = range(numero_righe)
R = range(numero_colonne)
y = mod.addVars(L,vtype=GRB.BINARY,name="y")
x = mod.addVars(R,vtype=GRB.BINARY,name="x")


# Creazione dell'obiettivo
obj = mod.setObjective(gp.quicksum(y[i] for i in L) - alpha * gp.quicksum((1-s[j])*x[j] for j in R), GRB.MINIMIZE)


#vincoli
for j in R:  
    if s[j]==1: #aggiungo per forza i punti importanti
        SU=1;
        #mod.addConstr(gp.quicksum(A[i,j]*y[i] for i in L) >= 1)
    else:     #altrimenti, il punto è generale e la sua appartenza alla soluzione dipende da alpha
        mod.addConstr(gp.quicksum(A[i,j] * y[i] for i in L) >= x[j]) 
    for i in L:
        mod.addConstr((A[i,j]*y[i])<=x[j])  #se posiziono la telecamera devo segnare i punti coperti

# Risoluzione del problema
mod.optimize()
    

Gurobi Optimizer version 10.0.3 build v10.0.3rc0 (win64)

CPU model: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 4 physical cores, 8 logical processors, using up to 8 threads

Optimize a model with 8659150 rows, 7752 columns and 8709601 nonzeros
Model fingerprint: 0x5401b23d
Variable types: 0 continuous, 7752 integer (7752 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+00]
  Objective range  [2e-01, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [0e+00, 0e+00]
Found heuristic solution: objective 0.0000000
Presolve removed 8654594 rows and 1919 columns
Presolve time: 4.68s
Presolved: 4556 rows, 5833 columns, 23572 nonzeros
Found heuristic solution: objective -112.0000000
Variable types: 0 continuous, 5833 integer (5833 binary)

Root simplex log...

Iteration    Objective       Primal Inf.    Dual Inf.      Time
       0   -8.9560000e+02   2.627000e+03   0.000000e+00      6s
    3798   -8.3022971e+02   0.000000e+00 

In [5]:
puntivisti=0;
    
for j in R:
    puntivisti=puntivisti+int(x[j].x)

puntiimportanti=0;
    
for j in range(numero_colonne):
    puntiimportanti=puntiimportanti+s[j]

telecameremesse=0;
for i in L:
    telecameremesse=telecameremesse+int(y[i].x)
    
print("X_LB ",puntivisti) #punti coperti
print("Y_LB ",telecameremesse) 
print("numero punti importanti: ",puntiimportanti) 

X_LB  6075
Y_LB  384
numero punti importanti:  50.0
